title: Services
description: Explore the range of services I offer as a sports multimedia journalist, from dynamic photography sessions to engaging videography projects. Whether you're an athlete looking to showcase your skills or a couple wanting to capture your special day, I have the expertise to bring your vision to life.
links:
  - label: View projects I've worked on as a sports multimedia journalist
    size: md
events:
  - category: Photography
    title: "Family Portrait Sessions"
    description: "Capture candid moments of your family with personalized portrait sessions"
    url: "/gallery#family-portraits"
  - category: Photography
    title: "Senior Athlete Compendium"
    description: "Celebrate your athletic journey with dynamic senior portraits on and off the field"
    url: "/gallery#senior-athletes"
  - category: Videography
    title: "Highlight Reels"
    description: "Showcase your athletic prowess with dynamic highlight reels that capture your best moments in action"
    url: "/gallery#highlight-reels"
  - category: Videography
    title: "Wedding Films"
    description: "Relive your special day with cinematic wedding films that tell your unique love story"
    url: "/gallery#wedding-films"
  - category: Social Media
    title: "Content Creation for Athletes"
    description: "Elevate your personal brand with engaging social media content tailored for athletes"
    url: "https://www.instagram.com/rytermedia/"
